---
title: "R Notebook"
output: html_notebook
---

## 1. Biomass analysis

```{r, include=FALSE}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library(lubridate)
library(GGally)
```


# read and check
```{r}
info_raw <- 
  read.csv("C:\\GitHubRepos\\Arbitrator\\Analysis\\Biomass_N_merged_WheatMaize.csv")
info_raw$X <- NULL

summary(info_raw)

```

# check formats
```{r}
info_work <- info_raw %>%
  mutate(HarvestDate = ymd(HarvestDate)) %>%
  mutate(Plot = factor(Plot)) %>%
  mutate(Block = factor(Block)) %>%
  mutate(NitroTreat = factor(NitroTreat, 
                             levels = c("Low N","Median N","High N"))) %>%
  mutate(Organ = factor(Organ, 
                             levels = c("Leaf","Stem","Grain", "Rachis", "Husk", "Senesced"))) %>%
  mutate(WaterTreat = factor(WaterTreat, 
                             levels = c("Dryland","Irrigated")))

str(info_work)
```

```{r}
summary(info_work)
```

# calculate Totals (bio and N)

```{r, fig.width=12, fig.height=8}

df_bio_sum <- info_work %>% 
#  na.omit() %>%
  dplyr::select(HarvestDate, Crop, Organ, NitroTreat, WaterTreat, Block,BiomassWeight) %>%
  tidyr::spread(Organ, BiomassWeight)  %>%
  rowwise() %>%
  mutate(Total = sum(Grain,Leaf,Rachis,Husk,Senesced, Stem, na.rm=TRUE)) %>% 
  mutate(Variable = "Biomass") %>%
  dplyr::select(Variable, HarvestDate, Crop, NitroTreat, WaterTreat, Block, Total) %>%
  mutate(Variable = as.factor(Variable))

df_N_sum <- info_work %>% 
#  na.omit() %>%
  dplyr::select(HarvestDate, Crop, Organ, NitroTreat, WaterTreat, Block,NitrogenWeight) %>%
  tidyr::spread(Organ, NitrogenWeight) %>%
  rowwise() %>%
  mutate(Total = sum(Grain,Leaf,Rachis,Husk,Senesced, Stem, na.rm=TRUE)) %>% 
  mutate(Variable = "Nitrogen") %>%
  dplyr::select(Variable, HarvestDate, Crop, NitroTreat, WaterTreat, Block, Total)

df_sum <- rbind(df_bio_sum, df_N_sum)


summary(df_sum)

```

## Do averages

```{r,fig.width=12, fig.height=10, warning=FALSE}
df_av <- df_sum %>%
  spread(Variable, "Total") %>%
  mutate(N_Perc_Tot = Nitrogen/Biomass*100) %>%
  gather("Variable","Total",Biomass:N_Perc_Tot)%>%
  mutate(Total = ifelse(Variable == "Biomass",Total/1000, Total)) %>%
  group_by(Variable, HarvestDate, Crop, NitroTreat, WaterTreat) %>%
  summarise(MeanValue = mean(Total), SdValue = sd(Total)) %>%
  ungroup() %>%
  mutate(Variable=factor(Variable, 
                            levels=c("Biomass","Nitrogen","N_Perc_Tot"), 
                            labels=c("Biomass (t/ha)","Nitrogen (kg/ha)","Nitrogen in biomass (%)")))
  


df_av %>%
  ggplot(aes(x=HarvestDate, y=MeanValue, colour = WaterTreat,
             linetype = NitroTreat,
             shape = NitroTreat)) +
  geom_point(size=3) +
  geom_line(size=1.1) +
  scale_shape(solid = FALSE)+
#  geom_smooth(aes(linetype=NitroTreat)) +
  geom_errorbar(aes(ymin=MeanValue-SdValue/2,
                    ymax=MeanValue+SdValue/2), width = 2) +
  facet_grid(Variable~Crop, scales="free") +
#  ylab("Nitrogen percentage (%) Total N in biomass (kg DM/ha) Total biomass (t N/ha)") +
  ylab("Average values")+
  theme(text = element_text(size=20))+
  theme(legend.title=element_blank()) +
  xlab("Sampling date") +
#  theme(legend.position="none")+
  scale_linetype_manual(values = c("dotted", "dashed", "solid","dotted", "dashed", "solid")) 
# + 
#   theme(strip.background = element_blank(),
#        strip.text.y = element_blank())


```


# Nitrogen percentages
```{r, fig.width=12, fig.height=20, warning=FALSE}

# Bio_Nperc_av <- info_work %>%
#   dplyr::select(-NitrogenWeight, -Block, -Plot)%>%
#   group_by(HarvestDate, Organ, Crop, NitroTreat, WaterTreat) %>%
#   summarise_each(funs(mean, sd)) %>%
#   gather("Variable", "Value", )
# 
# Bio_Nperc_av %>%
#   ggplot(aes(x=, y=BiomassWeight_mean, linetype=NitroTreat, colour = WaterTreat)) +
#   geom_smooth(aes(fill=NitroTreat),linetype=0) +
#   geom_point(aes(shape = NitroTreat),size=3) +
#   geom_line(size=1.1) +
#   scale_shape(solid = FALSE)+
# #  geom_smooth(aes(linetype=NitroTreat)) +
#   # geom_errorbar(aes(ymin=BiomassWeight_mean-BiomassWeight_sd/2,
#   #                   ymax=BiomassWeight_mean+BiomassWeight_sd/2), width = 2) +
#   facet_grid(Organ~Crop, scales="free") +
#   ylab("Nitrogen percentage in drymatter (%)") +
#   theme(text = element_text(size=20))+
#   theme(legend.title=element_blank()) +
#   xlab("Sampling date") +
# #  theme(legend.position="none")+
#   scale_linetype_manual(values = c("dotted", "dashed", "solid","dotted", "dashed", "solid"))


```
