---
title: "R Notebook"
output: html_notebook
---

# load libs
```{r, echo=FALSE, include=FALSE}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library(lubridate)
library(GGally)
```


## Maize data
```{r}

maize_cover_raw <- 
  read.table("K:\\Rainshelter\\Maize 2012-13\\Analysis\\WorkedData\\LightInterception\\CoverForR_maize.txt", header=TRUE)

summary(maize_cover_raw)
```

# Tidy up and clean
```{r}

# maize
maize_cover_work <- maize_cover_raw %>%
  mutate(Block = as.factor(Block)) %>%
  mutate(HarvestDate = dmy(Date), Crop = "Maize",
         Nitrogen =  as.numeric(as.character(gsub("N","",NitroTreat))),
         NitroTreat = factor(NitroTreat,levels = c("000N","075N","250N"), 
                             labels= c("Low N","Median N","High N")),
         WaterTreat = as.factor(WaterTreat) ,
         Irrigation = as.factor(WaterTreat)) %>%
  dplyr::select(-Nitrogen,-Irrigation,-Date)%>%
  mutate(Crop = factor(Crop))

# graph
maize_cover_work %>%
  ggplot(aes(x=HarvestDate, y=Cover, colour = WaterTreat, shape=NitroTreat)) +
  geom_point() +
  geom_smooth(aes(linetype=NitroTreat))

```



# Wheat data
```{r}

wheat_cover_raw <- 
  read.table("K:\\Rainshelter\\Wheat 2015-16\\Analysis\\LightInterception\\CoverForR.txt", header=TRUE)

summary(wheat_cover_raw)

```



```{r}
# wheat
 wheat_cover_work <- wheat_cover_raw %>%
  mutate(HarvestDate = dmy(Date), Crop = "Wheat") %>%
  mutate(Block = as.factor(Block),
         NitroTreat = factor(NitroTreat,levels = c(0,50,250), 
                             labels= c("Low N","Median N","High N"))) %>%
  dplyr::select(-Date)%>%
  mutate(Crop = factor(Crop))

# graph
wheat_cover_work %>%
  ggplot(aes(x=HarvestDate, y=Cover, colour = WaterTreat, shape=NitroTreat)) +
  geom_point() +
  geom_smooth(aes(linetype=NitroTreat))
```

## Merge
```{r}

cover_maize_wheat_merge <- rbind(maize_cover_work,wheat_cover_work)

cover_maize_wheat_merge <- cover_maize_wheat_merge %>% 
  mutate(codePlot = paste0(Crop,"_",WaterTreat,"_", NitroTreat,"_",Block))

summary(cover_maize_wheat_merge)

```

# graph to check

```{r}
cover_maize_wheat_merge %>%
  ggplot(aes(x=HarvestDate, y=Cover, colour=WaterTreat, linetype=NitroTreat)) +
 # geom_point() +
  geom_line() +
  facet_wrap(Crop~Block, scales="free", ncol=4)
```

# remove bad readings

```{r}
length(unique(cover_maize_wheat_merge$HarvestDate))

cover_maize_wheat_merge <-  cover_maize_wheat_merge %>%
  filter(HarvestDate !="2013-01-08") %>%
  filter(HarvestDate != "2015-11-17")  %>%
  filter(HarvestDate != "2015-12-11")      
    
length(unique(cover_maize_wheat_merge$HarvestDate))
```

# check clean data
```{r}
cover_maize_wheat_merge %>%
  ggplot(aes(x=HarvestDate, y=Cover, colour=WaterTreat, shape=NitroTreat)) +
 # geom_point() +
  geom_line(aes(linetype=NitroTreat)) +
  scale_linetype_manual(values = c("dotted", "dashed", "solid","dotted", "dashed", "solid")) +
  facet_wrap(Crop~Block, scales="free", ncol=4)
```

# graph averages

```{r}
# maize
av_sd <- cover_maize_wheat_merge %>% 
  group_by(Crop, HarvestDate, NitroTreat, WaterTreat) %>%
  summarise(mean = mean(Cover), sd = sd(Cover))

#str(lai_av_maize_wheat)
summary(av_sd)

x <- unique(cover_maize_wheat_merge$HarvestDate)
datesCover <- data.frame(Count= 1:length(x), HarvestDate = x)
write.csv(datesCover, "C:\\GitHubRepos\\Arbitrator\\Analysis\\DatesCoverSample.csv")

```
```{r,fig.width=12, fig.height=8}
av_sd %>%
  ggplot(aes(x=HarvestDate, y=mean, colour = WaterTreat, 
             linetype = NitroTreat,
             shape = NitroTreat)) +
  geom_point(size=3) +
 # geom_line(size=1.1) +  
  geom_smooth(alpha=0.1, aes(fill=WaterTreat))+
  scale_shape(solid = FALSE) +
  scale_linetype_manual(values = c("dotted", "dashed", "solid","dotted", "dashed", "solid")) +
  geom_errorbar(aes(ymin=mean-sd/2,
                    ymax=mean+sd/2), width = 2) +
  facet_grid(.~Crop, scales="free") +
  ylab("Sampling date") +
  ylab("Fractional light interception (fr, 0-1)") +
  theme(text = element_text(size=20))+
  theme(legend.title=element_blank()) +
  xlab(" ") + 
  ylim(0,1.2) +
  theme(legend.position=c(0.1, 0.8),legend.background = element_rect(fill=alpha('white', 0.1))) +   guides(fill = guide_legend(keywidth = 4, keyheight = 1))
```

# Interpolate by day

```{r}

# Loop crops, treatments and blocks (i.e. per plot analysis)

codePlotValues <- unique(cover_maize_wheat_merge$codePlot)

finalOutDf <- thisOutDf <- data.frame()

for(cp in 1:length(codePlotValues)) {
  
    df <- cover_maize_wheat_merge %>% 
      filter(codePlot == codePlotValues[cp]) %>% 
      ungroup() %>%
      na.omit()
    
    # find boundaries
    thisSeq <- seq(min(df$HarvestDate),max(df$HarvestDate),1)
    
   # out <- approx(df$HarvestDate, df$Cover, xout = thisSeq)
    
  # create a smoothed set of data
  dat <- df %>%
  mutate(doy=HarvestDate-min(HarvestDate)+1) %>%
  mutate(x=doy,y=Cover) %>%
  dplyr::select(x,y, HarvestDate)  %>%
  arrange(x)
  
  dat$x <- as.numeric(dat$x)
  dat$y <- as.numeric(dat$y)

  n=nrow(dat)

  loessData <- data.frame(
    x = 1:n,
    y = predict(loess(y~x, dat, span = 1)),
    HarvestDate = dat$HarvestDate
  )

  loessData <- loessData %>% dplyr::select(-x)
    
  # create the interpolation fundction  
  # outFun <- approxfun(df$HarvestDate, df$Cover, method = "linear")
   outFun <- approxfun(loessData$HarvestDate, loessData$y, method = "linear")

  #  thisOutDf <- data.frame(HarvestDate = out$x, Cover = out$y)
    
   thisOutDf <- data.frame(HarvestDate = thisSeq, Cover = outFun(thisSeq))
    

    thisOutDf <- thisOutDf %>%
      mutate(Crop = unique(df$Crop), 
                   WaterTreat = unique(df$WaterTreat), 
                   NitroTreat = unique(df$NitroTreat),  
                   Block = unique(df$Block)
             )
 
    # create and append results
    if(cp==1) {finalOutDf <- thisOutDf} else
      {finalOutDf <- rbind(finalOutDf,thisOutDf)}
 
}




```
## Clean and save

```{r}
# Make negative interception as zero
finalOutDf$Cover <- ifelse(finalOutDf$Cover<0,0,as.numeric(finalOutDf$Cover))

summary(finalOutDf)

 write.csv(finalOutDf, "C:\\GitHubRepos\\Arbitrator\\Analysis\\CoverInterpolatedByDay.csv")
```

# graph to check
```{r,fig.width=12, fig.height=8}

finalOutDf %>%
  ggplot(aes(x=HarvestDate, y=Cover, colour=WaterTreat, shape=NitroTreat)) +
  geom_line(aes(linetype=NitroTreat)) +
  geom_point(data=cover_maize_wheat_merge,aes(x=HarvestDate, y=Cover)) +
  scale_linetype_manual(values = c("dotted", "dashed", "solid","dotted", "dashed", "solid")) +
  facet_wrap(Crop~Block, scales="free", ncol=4)
  
```


