---
title: "R Notebook"
output: html_notebook
---

* Read LAI data
* Read daily interpolated interception data
* lookup interception per LAI
* calculate k

```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
library(lubridate)
```



```{r}

rootFolder <- "C:\\GitHubRepos\\Arbitrator\\Analysis\\"

```

LAI data
```{r}
lai_raw <- read.csv(paste0(rootFolder,"lai_maize_wheat.csv"), header = TRUE) %>%
  dplyr::select(-X) %>%
  mutate(NitroTreat=factor(NitroTreat,levels=c("Low N","Median N","High N"))) %>%
  mutate(Block=factor(Block)) %>%
  mutate(HarvestDate=ymd(HarvestDate))

summary(lai_raw)
```

```{r, fig.width=12, fig.height=10}
lai_raw %>%
  ggplot(aes(x=HarvestDate,y=LAI, colour=WaterTreat, linetype=Block)) +
  geom_point() +
  geom_line()+
  facet_grid(NitroTreat~Crop, scales='free')
```



Interception data (daily interpolated)

- FIXME: use a smooth interpolation method to remove bias from ind readings

```{r}
int_raw <- read.csv(paste0(rootFolder,"CoverInterpolatedByDay.csv"), header = TRUE)  %>%
  dplyr::select(-X) %>%
  mutate(NitroTreat=factor(NitroTreat,levels=c("Low N","Median N","High N"))) %>%
  mutate(Block=factor(Block)) %>%
  mutate(HarvestDate=ymd(HarvestDate))
  
summary(int_raw)
```

# merge

```{r}

lai_int <- merge(lai_raw,int_raw,
                 by=c("Crop","HarvestDate","WaterTreat","NitroTreat","Block")) 

summary(lai_int)

```

# inspect

```{r, fig.width=12, fig.height=15}
lai_int %>%
  ggplot(aes(x=LAI,y=Cover, colour=WaterTreat, shape=Block, linetype=WaterTreat)) +
  geom_point() +
  geom_line() +
  facet_grid(NitroTreat+Block~Crop)
```

