---
title: "R Notebook"
output: html_notebook
---

# load libs
```{r, echo=FALSE, include=FALSE}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library(lubridate)
library(GGally)
```

# Load maize data

```{r}
maize_lai_raw <- 
  read.table("K:\\Rainshelter\\Maize 2012-13\\Analysis\\WorkedData\\LAI\\LAI_Maize_R.txt", header=TRUE)

summary(maize_lai_raw)
```

## Tidy up and check maize lai
```{r}
maize_lai_work <- maize_lai_raw %>%
  mutate(Block = as.factor(Block),
         Trt = as.factor(Trt),
         Plot = as.factor(Plot)
         ) %>%
  mutate(HarvestDate = dmy(Date), Crop = "Maize",
         Nitrogen =  as.numeric(as.character(gsub("N","",NitroTreat))),
         NitroTreat = factor(NitroTreat,levels = c("000N","075N","250N"), 
                             labels= c("Low N","Median N","High N")),
         WaterTreat = ifelse(WaterTreat=="Irrig", "Irrigated","Dryland"), # same as wheat
         WaterTreat = as.factor(WaterTreat) ,
         Irrigation = as.factor(WaterTreat))

# graph
maize_lai_work %>%
  ggplot(aes(x=HarvestDate, y=LAI, colour = WaterTreat, shape=NitroTreat)) +
  geom_point() +
  geom_smooth(aes(linetype=NitroTreat))
```

# Load wheat data

```{r}
wheat_lai_raw <- 
  read.table("K:\\Rainshelter\\Wheat 2015-16\\Analysis\\Biomass\\BiomassLAIData.txt", header=TRUE)

#str(wheat_bio_raw)

summary(wheat_lai_raw)
```

## Tidy up and graph 

```{r}
# clean up and massage
wheat_lai_work <- wheat_lai_raw %>%
  dplyr::select(HarvestDate,Plot,
                Block, Nitrogen,Irrigation,LAI) %>%
  mutate(HarvestDate = dmy(HarvestDate), Crop = "Wheat") %>%
  mutate(Block = as.factor(Block),
      #   Trt = as.factor(TreatNo),
         Plot = as.factor(Plot-100),
         WaterTreat = Irrigation,
         NitroTreat = factor(Nitrogen,levels = c(0,50,250), labels= c("Low N","Median N","High N"))) 

# graph
wheat_lai_work %>%
  ggplot(aes(x=HarvestDate, y=LAI, colour = WaterTreat, shape=NitroTreat)) +
  geom_point() +
  geom_smooth(aes(linetype=NitroTreat))

# CHECK: Very high LAI numbers for Block 2

```

# Calculate averages and sds
```{r}

# maize
maize_av <- maize_lai_work %>% 
  group_by(Crop, HarvestDate, NitroTreat, WaterTreat) %>%
  summarise(lai_mean = mean(LAI),lai_sd = sd(LAI))

# wheat
wheat_av <- wheat_lai_work %>% 
  group_by(Crop, HarvestDate, NitroTreat, WaterTreat) %>%
  summarise(lai_mean = mean(LAI),lai_sd = sd(LAI))

lai_av_maize_wheat <- rbind(maize_av,wheat_av)

#str(lai_av_maize_wheat)
summary(lai_av_maize_wheat)

```

# graph


```{r,fig.width=12, fig.height=8}
lai_av_maize_wheat %>%
  ggplot(aes(x=HarvestDate, y=lai_mean, colour = WaterTreat, 
             linetype = NitroTreat,
             shape = NitroTreat)) +
  geom_point(size=3) +
  geom_line(size=1.1) +  
  scale_shape(solid = FALSE)+
  scale_linetype_manual(values = c("dotted", "dashed", "solid","dotted", "dashed", "solid")) +
 #geom_smooth(alpha=0.2)+
  geom_errorbar(aes(ymin=lai_mean-lai_sd/2,
                    ymax=lai_mean+lai_sd/2), width = 2) +
  facet_grid(.~Crop, scales="free") +
  ylab("Sampling date") +
  ylab("Leaf Area Index (LAI)") +
  theme(text = element_text(size=20))+
  theme(legend.title=element_blank()) +
  xlab(" ") + 
  theme(legend.position=c(0.9, 0.8),legend.background = element_rect(fill=alpha('white', 0.1)))
```

