---
title: "R Notebook"
output: html_notebook
---

# load libs
```{r, echo=FALSE, include=FALSE}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library(lubridate)
library(GGally)
```

# Read interpolated cover values

```{r}
cover_raw <- 
  read.csv("C:\\GitHubRepos\\Arbitrator\\Analysis\\CoverInterpolatedByDay.csv", header=TRUE)

summary(cover_raw)
```

# sort out formats
```{r}
cover_work <- cover_raw %>%
  mutate(Block = as.factor(Block)) %>%
  mutate(HarvestDate = ymd(HarvestDate),
         WaterTreat = as.factor(WaterTreat) ,
         WaterTreat = factor(WaterTreat, 
                             levels= c("Dryland","Irrigated")),
         NitroTreat = as.factor(NitroTreat),
         NitroTreat = factor(NitroTreat, 
                             levels= c("Low N","Median N","High N"))) %>%
  dplyr::select(-X)

str(cover_work)
```

# Check data
```{r,fig.width=12, fig.height=8}
cover_work %>%
  ggplot(aes(x=HarvestDate, y=Cover, colour=WaterTreat, shape=NitroTreat)) +
  geom_line(aes(linetype=NitroTreat)) +
  scale_linetype_manual(values = c("dotted", "dashed", "solid","dotted", "dashed", "solid")) +
  facet_wrap(Crop~Block, scales="free", ncol=4)
```

## Read weather file

```{r}

metFolder <- "C:\\Apsim_dev\\Data\\MetFiles\\"

weather_raw <- read.table(paste0(metFolder,"lincoln.met"), skip = 6, header = TRUE, comment.char = "(", blank.lines.skip = TRUE)

summary(weather_raw)

```

# Add date field and tidy up

```{r}
weather_work <- weather_raw %>%
  mutate(thisDate = as.Date(day, origin = paste0(year,"-01-01"))) %>%
  mutate(thisDate = ymd(thisDate)) %>%
  filter(thisDate %in% cover_work$HarvestDate)

str(weather_work)
```
# check
```{r}
summary(weather_work)
```

# Estimate daily light interception

```{r}

ww <- weather_work %>% dplyr::select(thisDate,radn)

rad_sum_df <- merge(cover_work,ww, by.x = "HarvestDate", by.y="thisDate") %>%
  mutate(RadInt = radn*Cover) %>%
  group_by(Crop,WaterTreat,NitroTreat,Block) %>%
  mutate(RadIntSum = cumsum(RadInt))

summary(rad_sum_df)
```

# graph

```{r,fig.width=12, fig.height=8}
rad_sum_df %>%
  ungroup() %>%
  mutate(NitroTreat = factor(NitroTreat, 
                             labels= c("Low N","Median N","High N"))) %>%
  ggplot(aes(x=HarvestDate, y=RadIntSum, colour=WaterTreat, linetype=NitroTreat)) +
  geom_line() +
  scale_linetype_manual(values = c("dotted", "dashed", "solid","dotted", "dashed", "solid"))+
  facet_wrap(Crop~Block, scales="free", ncol=4)
```

#  RUE calculation

## Merge Biomass and Interception

```{r}

bio_raw <- read.csv("C:\\GitHubRepos\\Arbitrator\\Analysis\\Biomass_N_merged_WheatMaize.csv")

summary(bio_raw)

```

```{r}
# clean data
bio_work <- bio_raw %>%
  dplyr::select(-X,-NitrogenPerc,-NitrogenWeight) %>%
  mutate(Block = as.factor(Block),
         HarvestDate = ymd(HarvestDate),
         WaterTreat = as.factor(WaterTreat) ,
         WaterTreat = factor(WaterTreat, 
                             levels= c("Dryland","Irrigated")),
         NitroTreat = as.factor(NitroTreat),
         NitroTreat = factor(NitroTreat, 
                             levels= c("Low N","Median N","High N"))) %>%
  dplyr::select(HarvestDate, Crop, Organ, NitroTreat, WaterTreat, Block,BiomassWeight) %>%
  tidyr::spread(Organ,BiomassWeight) %>%
  rowwise() %>%
  mutate(TotalBiomass = sum(Grain,Leaf,Rachis,Senesced,Stem, na.rm=TRUE)) %>%
  dplyr::select(-(Grain:Stem))

summary(bio_work)
```


```{r}
rue_df <- merge(rad_sum_df)
```

